### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by Junky96** [HarvestCraft/CloudHarvestDirect#1]
Be sure to use a proxy or VPN before deploying.
SoundCloud has systems in place to watch for “bots” and other inhuman actions (like sending 5000 page requests within a 30 second window)

I’ve gotten ”Your blocked” messages after using the previous iteration of this software from Fancymalware where my IP was denied from using the site after attempting to harvest private links. Luckily clearing browser cache and cookies dealt with the issue, but for safety I would suggest staying logged out of your SC account and masking your IP so you don’t get permanently banned or removed from the server on your personal network or device.

![IMG_1114](https://github.com/user-attachments/assets/8790f764-66fb-4d57-bcc5-175ce12a5628)

**Comment by HarvestCraft** [comment]
This limit is only an Issue on the Fancemalware and other versions that check If the private links are still valid. I have removed this check and simply log all private links alive or dead. 
I have done billions of requests from the same IP and only ever hit a rate limit and IP issue when I attempted to make a validator.

**Comment by HarvestCraft** [comment]
My version is drastically different.

**Comment by Junky96** [comment]
After testing, I can strongly confirm that this software is far superior to any previous iteration. This is great work.

Well done, thank you!
