### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by Junky96** [HarvestCraft/CloudHarvestDirect#2]
Not sure if this is user error or not, but the script was running great for about 9 hours yesterday.

I had an artist file running, and got a hit on a private link. I saved my state, hit stop so the link document would export (expecting it to export to the CloudHarvestDirect folder which it had previously done that morning), but it was nowhere to be found.

After digging around my PC for a bit, I found that the link export txt documents were now being saved to C:\Users\profile for some reason.

Then, after testing the script a bit more, I realized that the link documents (and at random times the save states) are no longer being saved in either folder. 

I'm now getting permission error messages and cannot figure out why.

Any ideas?

Error messages:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\arman\Documents\Python Scripts\CloudHarvestDirect-main\Beta3.py", line 276, in save_state
    with open('state.json', 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'state.json'
Exception in thread Thread-7 (saver_thread):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\arman\Documents\Python Scripts\CloudHarvestDirect-main\Beta3.py", line 124, in saver_thread
    f = open(output_filename, "a")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'output_20241104_175756.txt'
```

**Comment by Despaironleaked** [comment]
doesnt matter all links you will get are dead soundcloud changed the link parameters and reset all links

**Comment by Junky96** [comment]
> doesnt matter all links you will get are dead soundcloud changed the link parameters and reset all links

Any idea what the new parameters are?

Edit: Looks like shortened private links are 17 characters long. I believe this method would still work, but you would need a pretty powerful computer to go from aaaaaaaaaaaaaaaaa to 00000000000000000 within a reasonable timeframe.
Depending on an individuals PC specs, this could take months or even years.. Not to mention having a clogged up network during the entire process. But I do think it could work.

I'll fresh install this script to see if I get any hits using my own private links and will post the results.

**Comment by Despaironleaked** [comment]
> > doesnt matter all links you will get are dead soundcloud changed the link parameters and reset all links
> 
> Any idea what the new parameters are?
> 
> Edit: Looks like shortened private links are 17 characters long. I believe this method would still work, but you would need a pretty powerful computer to go from aaaaaaaaaaaaaaaaa to 00000000000000000 within a reasonable timeframe. Depending on an individuals PC specs, this could take months or even years.. Not to mention having a clogged up network during the entire process. But I do think it could work.
> 
> I'll fresh install this script to see if I get any hits using my own private links and will post the results.

you wont get anywhere already did the math it will take upwards of 20 years to complete a full attempt so unless you have a quantum computer it isnt worth it

**Comment by Junky96** [comment]
> > > doesnt matter all links you will get are dead soundcloud changed the link parameters and reset all links
> 
> > 
> 
> > Any idea what the new parameters are?
> 
> > 
> 
> > Edit: Looks like shortened private links are 17 characters long. I believe this method would still work, but you would need a pretty powerful computer to go from aaaaaaaaaaaaaaaaa to 00000000000000000 within a reasonable timeframe. Depending on an individuals PC specs, this could take months or even years.. Not to mention having a clogged up network during the entire process. But I do think it could work.
> 
> > 
> 
> > I'll fresh install this script to see if I get any hits using my own private links and will post the results.
> 
> 
> 
> you wont get anywhere already did the math it will take upwards of 20 years to complete a full attempt so unless you have a quantum computer it isnt worth it

LOL well damn. That's super unfortunate cause this little tool really had some thought put behind it. If anyone gets their hands on a quantum computer, let me know

**Comment by HarvestCraft** [comment]
17x links work with the beta version and i have a more refined version but after running it for 10 days i found one singular link and it was public. 

with their being no patterns I attempted a few randomizing algorithms that could be recreated and tracked but its on the back burner because like stated above.... 15-20 years to even get close to one pass thu when i could do the x5 pass thru in 3 days



this is most likely dead. i dabble with trying to figure out 17 x here and there but Its years away from being programmatically possible

**Comment by Junky96** [comment]
> 17x links work with the beta version and i have a more refined version but after running it for 10 days i found one singular link and it was public. 
> 
> 
> 
> with their being no patterns I attempted a few randomizing algorithms that could be recreated and tracked but its on the back burner because like stated above.... 15-20 years to even get close to one pass thu when i could do the x5 pass thru in 3 days
> 
> 
> 
> 
> 
> 
> 
> this is most likely dead. i dabble with trying to figure out 17 x here and there but Its years away from being programmatically possible 

Thank you for getting in touch and thank you for the hard work you put into this project. 
It was beautiful 🙏

**Comment by HarvestCraft** [comment]
twas a fun summer with this one. i got a full TB of songs.

**Comment by Despaironleaked** [comment]
> 17x links work with the beta version and i have a more refined version but after running it for 10 days i found one singular link and it was public.

private links still get pulled ive tried it with a burner account after they changed the links in june and it pulled it right away. the reason you got a public one is it was previously a private track. still wont change the how long it will take but figured id give you the info
